### ISSUE TITLE
Missing enhanced resolve

### ISSUE THREAD

**Issue by jquense** [niieani/webpack-dependency-suite#1]
hey there, neat set of tools. looks like you're missing `enhanced-resolve` in the package.json

**Comment by niieani** [comment]
That's true, although it is implicitly there, since you need Webpack to use this, and `enhanced-resolve` is a dependency thereof. For that matter, I'm also missing `webpack` itself as a dependency! :) 

I'll add it!

**Comment by jquense** [comment]
npm being npm, we didn't have enhanced resolve locally, hence the issue. maybe it makes more sense for it to be a direct dependency tho? unless there is a strong reason why you can't have more than one around
