### ISSUE TITLE
Globbing in comment-loader

### ISSUE THREAD

**Issue by jods4** [niieani/webpack-dependency-suite#2]
Globbing doesn't work in comment only imports, like `/* @import('*.ts') */`.
Reason is that the Regex doesn't match `*`.
You should change the Regex on [line 90](https://github.com/niieani/webpack-dependency-suite/blob/master/loaders/comment-loader.ts#L90)
```js
// now
/^@import\([\'"`]*([- \./\w]+)['"`]\)* *(@lazy)? *(?:@chunk\(['"`]*([\w-]+)['"`]*\))? *(@lazy)?$/
// fixed
/^@import\([\'"`]*([- \./\w*]+)['"`]\)* *(@lazy)? *(?:@chunk\(['"`]*([\w-]+)['"`]*\))? *(@lazy)?$/
                           ^
```
It then works for me.
Other parts of this regex look strange to me, like the star after import's opening quote or closing bracket.

After globbing, the next step is resolving paths and it fails on Windows, because the absolute paths of matching files use `\`. I had to fix it by replacing every `\` with a `/`.
```js
resourceData.forEach(r => r.literal = r.literal.replace(/\\/g, "/"));
```

**Comment by niieani** [comment]
Nice catch. I'll try to get a fix in soon.
