### ISSUE TITLE
Check also peerDependencies in RootMostResolvePlugin

### ISSUE THREAD

**Issue by zinserjan** [niieani/webpack-dependency-suite#6]
RootMostResolvePlugin fails for packages where the dependency isn't listed in the dependencies block and when there is no dependencies block.

I have some packages in my lerna repo where `react` is listed as a peerDependency and for development purposes it's also listed as devDependency.

```json
{
  "devDependencies": {
    "babel-cli": "^6.22.2",
    "babel-preset-es2017": "^6.22.0",
    "enzyme": "^2.7.1",
    "enzyme-to-json": "^1.5.0",
    "jest": "^19.0.2",
    "react": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2",
    "rimraf": "^2.5.4"
  },
  "peerDependencies": {
    "react": "^15.4.2"
  }
}
```

The plugin fails with something like `Can not read 'react' of undefined`.

Tasks to fix this:
- check if dependencies block exists and if the package is listed there
- when not, check if a peerDependencies block exists and if the package is listed there

**Comment by niieani** [comment]
As mentioned in #7, I'm not going to have time to do this in the next few weeks, but I'd welcome a PR.
